- name: Install php5.6
  sudo: yes
  yum: pkg=php state=latest enablerepo=remi-php56

- name: ensure timezone is set in apache2 php.ini
  lineinfile: dest=/etc/php.ini
              regexp='date.timezone ='
              line='date.timezone = {{ timezone }}'
