- name: Install require package to install PHP Packages
  sudo: yes
  yum: name={{ item }} state=latest enablerepo=epel
  with_items:
    - libmcrypt

- name: Install PHP Packages
  sudo: yes
  yum: pkg={{ item }} state=latest enablerepo=remi-php56
  notify: restart apache
  with_items: php_packages
